/**
 * PDF Report Generator for FreshTrack
 * Called by server.js: require('./routes/pdfReport')(app, models)
 * 
 * Design principles:
 *  - No emoji / unicode icons (render as broken boxes in PDFs)
 *  - Single brand color (indigo) used consistently for all section headers
 *  - Right-aligned number columns
 *  - Consistent "Rs. X.XX" currency format
 *  - Readable font sizes (body >= 10pt, headings 14-16pt)
 *  - Page numbers in footer
 */

const PDFDocument = require('pdfkit');

// ── Colours ──────────────────────────────────────────────────
const BRAND      = '#4f46e5';   // indigo — single accent used everywhere
const MUTED      = '#6b7280';   // grey
const BLACK      = '#111827';
const SUBTLE_BG  = '#f5f5ff';   // very light indigo tint for alt rows
const HEADER_BG  = '#e8e9ff';   // section heading background

// ── Helpers ──────────────────────────────────────────────────
function fmtDate(d) {
  if (!d) return '-';
  return new Date(d).toLocaleDateString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric', timeZone: 'Asia/Kolkata'
  });
}

function fmtMoney(n) {
  return `Rs. ${(Number(n) || 0).toFixed(2)}`;
}

function fmtQty(qty, unitType) {
  if (unitType === 'packet') return `${qty} pkt`;
  return qty >= 1000 ? `${(qty / 1000).toFixed(2)} kg` : `${qty} g`;
}

// ── Page number tracking ─────────────────────────────────────
function addPageNumbers(doc) {
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(range.start + i);
    const pageNum = i + 1;
    const total   = range.count;
    const footerY = doc.page.height - 32;
    const pageW   = doc.page.width;

    // Footer line
    doc.save()
       .moveTo(40, footerY - 6).lineTo(pageW - 40, footerY - 6)
       .lineWidth(0.5).strokeColor('#d1d5db').stroke()
       .restore();

    doc.fillColor(MUTED).fontSize(8).font('Helvetica')
       .text(
         `Generated by FreshTrack POS`,
         40, footerY, { width: pageW - 80, align: 'left' }
       )
       .text(
         `Page ${pageNum} of ${total}`,
         40, footerY, { width: pageW - 80, align: 'right' }
       );
  }
}

// ── Table renderer ───────────────────────────────────────────
// alignments: array of 'left' | 'right' | 'center' per column
function drawTable(doc, { headers, rows, colWidths, alignments = [], x, y, rowHeight = 22 }) {
  const totalW = colWidths.reduce((s, w) => s + w, 0);

  // Guard against running off the bottom before we even start
  if (y > doc.page.height - 120) {
    doc.addPage();
    y = 60;
  }

  // ── Header row ──────────────────────────────────────────────
  doc.save().rect(x, y, totalW, rowHeight).fill(BRAND).restore();

  let cx = x;
  headers.forEach((h, i) => {
    const align = alignments[i] || 'left';
    const padL  = align === 'right' ? 2 : 4;
    const padR  = align === 'right' ? 6 : 4;
    doc.fillColor('#ffffff')
       .fontSize(8)
       .font('Helvetica-Bold')
       .text(h, cx + padL, y + 7, {
         width: colWidths[i] - padL - padR,
         align,
         lineBreak: false,
       });
    cx += colWidths[i];
  });
  y += rowHeight;

  // ── Data rows ────────────────────────────────────────────────
  rows.forEach((row, ri) => {
    const bg = ri % 2 === 0 ? '#ffffff' : SUBTLE_BG;
    doc.save().rect(x, y, totalW, rowHeight).fill(bg).restore();

    // Thin border around row
    doc.save()
       .rect(x, y, totalW, rowHeight)
       .lineWidth(0.25)
       .stroke('#d1d5db')
       .restore();

    cx = x;
    row.forEach((cell, ci) => {
      const text  = cell === null || cell === undefined ? '-' : String(cell);
      const align = alignments[ci] || 'left';
      const padL  = align === 'right' ? 2 : 4;
      const padR  = align === 'right' ? 6 : 4;

      // Bold only if it's a "Total" label cell
      const isTotalRow = typeof row[0] === 'string' && row[0].startsWith('TOTAL');

      doc.fillColor(BLACK)
         .fontSize(9)
         .font(isTotalRow ? 'Helvetica-Bold' : 'Helvetica')
         .text(text, cx + padL, y + 6, {
           width: colWidths[ci] - padL - padR,
           align,
           lineBreak: false,
         });
      cx += colWidths[ci];
    });

    y += rowHeight;

    // Page break guard
    if (y > doc.page.height - 80) {
      doc.addPage();
      y = 60;
    }
  });

  return y; // return new y position after table
}

// ── Section heading ──────────────────────────────────────────
// Renders: [colored square bullet] + Section Title + optional subtitle
function sectionHeading(doc, title, subtitle, y) {
  if (y > doc.page.height - 120) {
    doc.addPage();
    y = 60;
  }

  const pageW    = doc.page.width;
  const contentW = pageW - 80;

  // Heading background bar
  doc.save()
     .rect(40, y, contentW, 24)
     .fill(HEADER_BG)
     .restore();

  // Colored square bullet (instead of emoji)
  doc.save()
     .rect(44, y + 7, 8, 8)
     .fill(BRAND)
     .restore();

  // Title text
  doc.fillColor(BRAND)
     .fontSize(11)
     .font('Helvetica-Bold')
     .text(title, 58, y + 6, { lineBreak: false });

  y += 28;

  // Optional subtitle in muted gray
  if (subtitle) {
    doc.fillColor(MUTED)
       .fontSize(8.5)
       .font('Helvetica')
       .text(subtitle, 44, y, { lineBreak: false });
    y += 14;
  }

  return y;
}

// ── Empty state ───────────────────────────────────────────────
function emptyState(doc, msg, y) {
  doc.fillColor(MUTED)
     .fontSize(9)
     .font('Helvetica')
     .text(msg, 44, y);
  return y + 18;
}

// ── Summary card grid ─────────────────────────────────────────
function drawSummaryCards(doc, cards, cardW, startX, startY) {
  cards.forEach((c, i) => {
    const col = i % 3;
    const row = Math.floor(i / 3);
    const cx  = startX + col * (cardW + 6);
    const cy  = startY + row * 58;

    // Card background
    doc.save()
       .roundedRect(cx, cy, cardW, 52, 4)
       .fill('#f8f8ff')
       .restore();

    // Left accent strip
    doc.save()
       .rect(cx, cy, 3, 52)
       .fill(c.accentColor || BRAND)
       .restore();

    // Label
    doc.fillColor(MUTED)
       .fontSize(8)
       .font('Helvetica')
       .text(c.label.toUpperCase(), cx + 10, cy + 8, { lineBreak: false });

    // Value
    doc.fillColor(c.valueColor || BLACK)
       .fontSize(14)
       .font('Helvetica-Bold')
       .text(c.value, cx + 10, cy + 22, { lineBreak: false });
  });
}

// ── Main export ───────────────────────────────────────────────
module.exports = function registerPdfRoute(app, {
  Sale, Inventory, Wastage, Expense,
  Supplier, SupplierPayment, Customer, CreditSale, CreditPayment
}) {

  app.get('/api/reports/full-pdf', async (req, res) => {
    try {
      const { from, to } = req.query;
      if (!from || !to) return res.status(400).send('from and to query params required');

      const fromDate = new Date(from);
      fromDate.setHours(0, 0, 0, 0);
      const toDate = new Date(to);
      toDate.setHours(23, 59, 59, 999);

      const dateRange = { $gte: fromDate, $lte: toDate };

      // ── Fetch all data in parallel ─────────────────────────
      const [sales, inventory, wastage, expenses, suppliers, payments,
             customers, creditSales, creditPayments] = await Promise.all([
        Sale.find({ sold_at: dateRange }).populate('item_id').lean(),
        Inventory.find({ created_at: dateRange }).populate('supplier_id').lean(),
        Wastage.find({ wasted_at: dateRange }).populate('item_id').lean(),
        Expense.find({ expense_date: dateRange }).lean(),
        Supplier.find().lean(),
        SupplierPayment.find().lean(),
        Customer.find().lean(),
        CreditSale.find({ credit_date: dateRange }).lean(),
        CreditPayment.find().lean(),
      ]);

      // ── Financial totals ───────────────────────────────────
      const totalRevenue     = sales.reduce((s, r) => s + (r.total_amount || 0), 0);
      const totalCOGS        = sales.reduce((s, r) => s + (r.qty_sold * (r.cost_price_per_unit || 0)), 0);
      const grossProfit      = totalRevenue - totalCOGS;
      const totalExpenses    = expenses.reduce((s, e) => s + (e.amount || 0), 0);
      const totalWastageLoss = wastage.reduce((s, w) => s + (w.loss_value || 0), 0);
      const netProfit        = grossProfit - totalExpenses - totalWastageLoss;

      // ── Build PDF (buffered so we can add page numbers) ────
      const doc = new PDFDocument({
        margin: 40,
        size: 'A4',
        bufferPages: true,   // needed for page number pass
        info: { Title: 'FreshTrack Business Report', Author: 'FreshTrack POS' }
      });

      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition',
        `attachment; filename="FreshTrack_Report_${from}_to_${to}.pdf"`);
      doc.pipe(res);

      const pageW    = doc.page.width;
      const contentW = pageW - 80;

      // ╔══════════════════════════════════════════════╗
      // ║  HEADER                                      ║
      // ╚══════════════════════════════════════════════╝
      doc.rect(0, 0, pageW, 72).fill(BRAND);

      doc.fillColor('#ffffff')
         .fontSize(22)
         .font('Helvetica-Bold')
         .text('FreshTrack', 40, 16);

      doc.fillColor('rgba(255,255,255,0.75)')
         .fontSize(9.5)
         .font('Helvetica')
         .text('Business Report  |  Grocery POS', 40, 42);

      // Date range — right aligned
      const rangeText = `${fmtDate(fromDate)}  to  ${fmtDate(toDate)}`;
      doc.fillColor('#ffffff')
         .fontSize(9)
         .text(rangeText, pageW - 240, 20, { width: 200, align: 'right' });

      const genTime = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
      doc.fillColor('rgba(255,255,255,0.65)')
         .fontSize(8)
         .text(`Generated: ${genTime}`, pageW - 240, 36, { width: 200, align: 'right' });

      let y = 88;

      // ╔══════════════════════════════════════════════╗
      // ║  FINANCIAL SUMMARY CARDS                     ║
      // ╚══════════════════════════════════════════════╝
      y = sectionHeading(doc, 'Financial Summary', `Period: ${fmtDate(fromDate)} to ${fmtDate(toDate)}`, y);

      const cardW = Math.floor((contentW - 12) / 3);
      const summaryCards = [
        { label: 'Total Sales Revenue', value: fmtMoney(totalRevenue),    valueColor: BLACK,    accentColor: BRAND   },
        { label: 'Cost of Goods Sold',  value: fmtMoney(totalCOGS),       valueColor: MUTED,    accentColor: MUTED   },
        { label: 'Gross Profit',        value: fmtMoney(grossProfit),      valueColor: grossProfit >= 0 ? '#059669' : '#dc2626', accentColor: '#059669' },
        { label: 'Total Expenses',      value: fmtMoney(totalExpenses),    valueColor: '#dc2626', accentColor: '#dc2626' },
        { label: 'Wastage Loss',        value: fmtMoney(totalWastageLoss), valueColor: '#dc2626', accentColor: '#f59e0b' },
        { label: 'Net Profit',          value: fmtMoney(netProfit),        valueColor: netProfit >= 0 ? '#059669' : '#dc2626', accentColor: netProfit >= 0 ? '#059669' : '#dc2626' },
      ];
      drawSummaryCards(doc, summaryCards, cardW, 40, y);
      y += (Math.ceil(summaryCards.length / 3)) * 58 + 12;

      // Net profit emphasis line
      doc.save()
         .rect(40, y, contentW, 1)
         .fill('#e0e2f0')
         .restore();
      y += 10;

      // ╔══════════════════════════════════════════════╗
      // ║  SALES TABLE                                 ║
      // ╚══════════════════════════════════════════════╝
      y = sectionHeading(doc, `Sales Report`, `${sales.length} transaction(s) in selected period`, y);

      if (sales.length === 0) {
        y = emptyState(doc, 'No sales recorded in this period.', y);
      } else {
        const salesRows = sales.map(s => [
          fmtDate(s.sold_at),
          s.item_name || '-',
          fmtQty(s.qty_sold, s.unit_type),
          fmtMoney(s.total_amount),
          fmtMoney(s.profit),
        ]);
        // Add totals row
        salesRows.push([
          `TOTAL (${sales.length} sales)`,
          '',
          '',
          fmtMoney(totalRevenue),
          fmtMoney(grossProfit),
        ]);

        y = drawTable(doc, {
          headers:    ['Date', 'Item', 'Qty Sold', 'Revenue', 'Gross Profit'],
          rows:       salesRows,
          colWidths:  [78, 160, 68, 90, 90],
          alignments: ['left', 'left', 'left', 'right', 'right'],
          x: 40, y,
        }) + 14;
      }

      // ╔══════════════════════════════════════════════╗
      // ║  INVENTORY PURCHASES TABLE                   ║
      // ╚══════════════════════════════════════════════╝
      y = sectionHeading(doc, 'Inventory Purchases', `${inventory.length} purchase(s) in selected period`, y);

      if (inventory.length === 0) {
        y = emptyState(doc, 'No inventory purchases in this period.', y);
      } else {
        const totalInvCost = inventory.reduce((s, p) => s + (p.purchase_price_total || 0), 0);
        const invRows = inventory.map(p => [
          fmtDate(p.created_at),
          p.item_name || '-',
          p.unit_type === 'packet'
            ? `${p.total_packets_purchased || 0} pkts`
            : `${p.purchase_qty || 0} ${p.unit || 'kg'}`,
          fmtMoney(p.purchase_price_total),
          p.supplier_id?.supplier_name || '-',
        ]);
        invRows.push([`TOTAL (${inventory.length} purchases)`, '', '', fmtMoney(totalInvCost), '']);

        y = drawTable(doc, {
          headers:    ['Date', 'Item', 'Qty Purchased', 'Total Cost', 'Supplier'],
          rows:       invRows,
          colWidths:  [78, 148, 82, 90, 88],
          alignments: ['left', 'left', 'left', 'right', 'left'],
          x: 40, y,
        }) + 14;
      }

      // ╔══════════════════════════════════════════════╗
      // ║  WASTAGE / WRITE-OFFS                        ║
      // ╚══════════════════════════════════════════════╝
      y = sectionHeading(
        doc,
        'Wastage / Write-offs',
        `${wastage.length} write-off(s) — items lost due to spoilage or damage`,
        y
      );

      if (wastage.length === 0) {
        y = emptyState(doc, 'No wastage recorded in this period.', y);
      } else {
        const wastageRows = wastage.map(w => [
          fmtDate(w.wasted_at),
          w.item_name || '-',
          fmtQty(w.qty_wasted, w.unit_type),
          fmtMoney(w.loss_value),
          w.reason || '-',
        ]);
        wastageRows.push([`TOTAL (${wastage.length} write-offs)`, '', '', fmtMoney(totalWastageLoss), '']);

        y = drawTable(doc, {
          headers:    ['Date', 'Item', 'Qty Wasted', 'Loss (at Cost)', 'Reason'],
          rows:       wastageRows,
          colWidths:  [78, 138, 78, 94, 98],
          alignments: ['left', 'left', 'left', 'right', 'left'],
          x: 40, y,
        }) + 14;
      }

      // ╔══════════════════════════════════════════════╗
      // ║  EXPENSES TABLE                              ║
      // ╚══════════════════════════════════════════════╝
      y = sectionHeading(
        doc,
        'Expenses',
        `${expenses.length} expense(s) — operational costs like rent, wages, transport`,
        y
      );

      if (expenses.length === 0) {
        y = emptyState(doc, 'No expenses recorded in this period.', y);
      } else {
        const expRows = expenses.map(e => [
          fmtDate(e.expense_date),
          e.expense_type || '-',
          fmtMoney(e.amount),
          e.notes || '-',
        ]);
        expRows.push([`TOTAL (${expenses.length} expenses)`, '', fmtMoney(totalExpenses), '']);

        y = drawTable(doc, {
          headers:    ['Date', 'Type', 'Amount', 'Notes'],
          rows:       expRows,
          colWidths:  [88, 110, 88, 200],
          alignments: ['left', 'left', 'right', 'left'],
          x: 40, y,
        }) + 14;
      }

      // ╔══════════════════════════════════════════════╗
      // ║  SUPPLIER DUES                               ║
      // ╚══════════════════════════════════════════════╝
      y = sectionHeading(
        doc,
        'Supplier Dues Summary',
        'Total purchased from each vendor vs. amount paid — shows outstanding balance',
        y
      );

      if (suppliers.length === 0) {
        y = emptyState(doc, 'No suppliers added yet.', y);
      } else {
        const supplierRows = await Promise.all(suppliers.map(async (sup) => {
          const purch = await Inventory.aggregate([
            { $match: { supplier_id: sup._id } },
            { $group: { _id: null, total: { $sum: '$purchase_price_total' } } }
          ]);
          const paid = await SupplierPayment.aggregate([
            { $match: { supplier_id: sup._id } },
            { $group: { _id: null, total: { $sum: '$amount_paid' } } }
          ]);
          const lastPay = payments
            .filter(p => String(p.supplier_id) === String(sup._id))
            .sort((a, b) => new Date(b.payment_date) - new Date(a.payment_date))[0];
          const totalPurch = purch[0]?.total || 0;
          const totalPaid  = paid[0]?.total || 0;
          return [
            sup.supplier_name,
            fmtMoney(totalPurch),
            fmtMoney(totalPaid),
            fmtMoney(totalPurch - totalPaid),
            fmtDate(lastPay?.payment_date),
          ];
        }));

        y = drawTable(doc, {
          headers:    ['Supplier Name', 'Total Purchased', 'Total Paid', 'Balance Owed', 'Last Payment'],
          rows:       supplierRows,
          colWidths:  [130, 94, 82, 90, 90],
          alignments: ['left', 'right', 'right', 'right', 'left'],
          x: 40, y,
        }) + 14;
      }

      // ╔══════════════════════════════════════════════╗
      // ║  CUSTOMER CREDIT / UDHAAR                    ║
      // ╚══════════════════════════════════════════════╝
      y = sectionHeading(
        doc,
        'Customer Credit / Udhaar Summary',
        'Credit given to customers vs. amount received back — shows pending dues',
        y
      );

      if (customers.length === 0) {
        y = emptyState(doc, 'No customers added yet.', y);
      } else {
        const custRows = await Promise.all(customers.map(async (cust) => {
          const cSales = await CreditSale.aggregate([
            { $match: { customer_id: cust._id } },
            { $group: { _id: null, total: { $sum: '$amount' } } }
          ]);
          const cPaid = await CreditPayment.aggregate([
            { $match: { customer_id: cust._id } },
            { $group: { _id: null, total: { $sum: '$amount_paid' } } }
          ]);
          const lastPay = creditPayments
            .filter(p => String(p.customer_id) === String(cust._id))
            .sort((a, b) => new Date(b.payment_date) - new Date(a.payment_date))[0];
          const totalCredit = cSales[0]?.total || 0;
          const totalPaid   = cPaid[0]?.total || 0;
          return [
            cust.customer_name,
            cust.phone_number || '-',
            fmtMoney(totalCredit),
            fmtMoney(totalPaid),
            fmtMoney(totalCredit - totalPaid),
            fmtDate(lastPay?.payment_date),
          ];
        }));

        y = drawTable(doc, {
          headers:    ['Customer', 'Phone', 'Total Credit', 'Paid Back', 'Pending', 'Last Payment'],
          rows:       custRows,
          colWidths:  [115, 82, 76, 72, 72, 69],
          alignments: ['left', 'left', 'right', 'right', 'right', 'left'],
          x: 40, y,
        }) + 14;
      }

      // ── Add page numbers across all pages ─────────────────
      addPageNumbers(doc);

      doc.end();

    } catch (err) {
      console.error('PDF generation error:', err);
      if (!res.headersSent) res.status(500).send(err.message);
    }
  });
};
